configReload:
  configURL: https://raw.githubusercontent.com/Weissnix4711/cube-services/master/config.yaml
  interval: 100000
targetConfigs:
  - url: https://github.com/Weissnix4711/cube-services
    targetPath: "services"
    branch: "main"
    schedule: "1/10 * * * * *"
  - url: https://github.com/Weissnix4711/cube-services
    targetPath: "systemd"
    branch: "main"
    schedule: "1/10 * * * * *"
