[http]

  [http.routers]

    [http.routers.dashboard]
      middlewares = ["dashboard-auth"]
      rule = "Host(`traefik.cube.thomasaldrian.net`)"
      service = "api@internal"

    [http.routers.truenas]
      rule = "Host(`nas.thomasaldrian.net`)"
      service = "truenas"

    [http.routers.pve]
      rule = "Host(`pve.cube.thomasaldrian.net`)"
      service = "pve"

    [http.routers.cthost]
      rule = "Host(`cthost.cube.thomasaldrian.net`)"
      service = "cthost"

    [http.routers.homeassistant]
      rule = "Host(`home.thomasaldrian.net`)"
      service = "homeassistant"

  [http.services]

    [http.services.truenas]
      loadBalancer.servers = [{ url = "https://truenas.cube.thomasaldrian.net" }]

    [http.services.pve]
      loadBalancer.servers = [{ url = "https://10.10.10.1:8006" }]

    [http.services.cthost]
      loadBalancer.servers = [{ url = "https://host.containers.internal:9090" }]

    [http.services.homeassistant]
      loadBalancer.servers = [{ url = "http://homeassistant.cube.thomasaldrian.net:8123" }]


# Serve 404 and ldaps with le certs
[tls.stores.default.defaultGeneratedCert]
  domain.main = "*.thomasaldrian.net"
  resolver = "le"


[tls.options.default]
  cipherSuites = [
    "TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
    "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
    "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256",
  ]
  minVersion = "VersionTLS12"
  sniStrict = true
